services:
  payload:
    image: 242912/payload:latest
    ports:
      - '8080:8080'
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules: