services:
  payload:
    image: 242912/payload:latest
    ports:
      - '8080:8080'
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  node_modules: