services:
  payload:
    image: 242912/payload:latest
    ports:
      - '8080:8080'
    volumes:
      - ./.env:/opt/app/.env
    command: sh -c "yarn payload:prod migrate:create && yarn payload:prod migrate && yarn serve"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  node_modules: