version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  node_modules:
