version: '3'

services:
  payload:
    image: node:18-alpine
    container_name: payload
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data:
  node_modules:
